services:
  # Apache
  apache:
    image: httpd:2.4
    container_name: ${PROJECT_NAME}_apache
    ports:
      - "8080:80"
    volumes:
      - ./${PROJECT_DIR}:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - php
  # PHP-FPM
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./${PROJECT_DIR}:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge
